name: Testing runner hierarchy
on:
  pull_request:
    types: [opened, ready_for_review]
    branches:
      - "dependabot/**"

jobs:
  print-versions:
    name: Print current package versions
    runs-on: [self-hosted, ubuntu-latest]
    steps:
      - run: dpkg -l | grep ii
