name: Testing runner hierarchy
on:
  workflow_dispatch:
jobs:
  print-versions:
    name: Print current package versions
    runs-on: [self-hosted, ubuntu-latest]
    steps:
      - name: show package versions
        run: dpkg -l | grep ii
